name: Qt Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts'
          
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Build Application
        run: |
          dir
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          qmake
        shell: cmd
