name: Qt Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts'
          
      - name: install-cmake
        uses: Symbitic/install-cmake@v0.1.0
        
      - name: Build Application
        run: |
          cd PieceOfShift
          mkdir build
          cd build
          cmake ..
          make
        shell: bash
